# Generated by Django 2.2.5 on 2019-09-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pick',
        ),
    ]
